version: '3.6'

services: 
 db:
  #image: postgres:9.6-alpine
  image: postgres:latest
  restart: always
  environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rust_db
  ports:
   - 5432:5432

 rust_db:
  build: .
  depends_on:
   - db
  environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - ROCKET_ADDRESS=127.0.0.1
      - ROCKET_PORT=4000
      - DATABASE_URL=postgres://username:password@db/rust_db
  ports:
   - "4000:4000"
